### ISSUE TITLE
Can't bundle install coz the gem `rb-inotify` 0.9.6 doesn't exist.

### ISSUE THREAD

**Issue by urimaro** [dtcristo/middleman-cactus#1]
### Steps to reproduce

`bundle install` after `middleman init -T dtcristo/middleman-cactus`
1. install `bundler`
2. `bundle init`  
   `Gemfile` is made.
3. edit `Gemfile`
   add `gem 'middleman'`
4. `bundle install`  
   `middleman` is installed.
5. `bundle exec middleman init -T dtcristo/middleman-cactus`
6. `bundle install`  
### Actual behavior

Following error has occurred coz the gem `rb-inotify` 0.9.6 doesn't exist on the RubyGems.org.
https://rubygems.org/gems/rb-inotify
https://github.com/nex3/rb-inotify/releases

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find rb-inotify-0.9.6 in any of the sources
```
### System configuration

**Ruby version**: 2.3.1p112
### Workaround
1. delete `Gemfile.lock`
2. bundle install

After than, new `Gemfile.lock` is created.
The `rb-inotify`'s version is bumped to 0.9.7.
Of course, the versions of other gems are bumped.

I think it's easier you'll update `Gemfile.lock` than I'll create the PR.
But you don't think so, I'll make it :smiley:

**Comment by dtcristo** [comment]
Thanks for finding this. Fixed by b71ec8d6a89b2c31f664aca74b0acfa9a8d7296b.
