### ISSUE TITLE
The style doesn't apply

### ISSUE THREAD

**Issue by urimaro** [dtcristo/middleman-cactus#2]
### Steps to reproduce
1. install `bundler`
2. `bundle init`  
   `Gemfile` is made.
3. edit `Gemfile`
   add `gem 'middleman'`
4. `bundle install`  
   `middleman` is installed.
5. `bundle exec middleman init -T dtcristo/middleman-cactus`
6. delete `Gemfile.lock`  
   see #1 
7. `bundle install`  
8. `bundle exec middleman`
### Actual behavior

The style isn't applied.
The Middleman-Sprockets seem not to work.
### System configuration

**Ruby version**: 2.3.1p112
### Workaround

Add `activate :sprockets` to `config.rb`.

The Middleman-Sprockets site says

``````
 To use, activate the extension in `config.rb`:

    ```ruby
    activate :sprockets
    ```
``````

See [Basic Usage](https://github.com/middleman/middleman-sprockets/blob/master/features/basic_usage.feature).

**Comment by dtcristo** [comment]
I've removed the dependency on sprockets in b71ec8d6a89b2c31f664aca74b0acfa9a8d7296b. It's not really supported by Middleman [anymore](https://middlemanapp.com/advanced/asset_pipeline/) and I wasn't using it for much.
